# Generated by Django 3.2.6 on 2022-01-14 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('phone', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], default='Applicant', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AddUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=60)),
                ('dob', models.TextField(max_length=9)),
                ('user_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='madmin.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='AddDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_sim', models.IntegerField(max_length=10)),
                ('secondary_sim', models.IntegerField(max_length=10)),
                ('firmware_option', models.CharField(choices=[('android', 'android'), ('apple', 'apple'), ('windows', 'windows')], default='android', max_length=50)),
                ('imei_number', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='madmin.myuser')),
            ],
        ),
    ]
