# Generated by Django 3.2.6 on 2022-01-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='phone',
        ),
        migrations.AlterField(
            model_name='adddevice',
            name='primary_sim',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='adddevice',
            name='secondary_sim',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], default='Admin', max_length=40),
        ),
    ]
