# Generated by Django 3.2.6 on 2022-01-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmin', '0002_auto_20220114_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddevice',
            name='imei_number',
            field=models.CharField(max_length=20),
        ),
    ]
