# Generated by Django 3.2.7 on 2021-09-27 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_auto_20210921_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=120, unique=True)),
                ('topic', models.CharField(max_length=120)),
                ('date', models.DateField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('topic_status', models.CharField(choices=[('in-progress', 'in-progress'), ('completed', 'completed')], default='in-progree', max_length=40)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.batch')),
            ],
        ),
    ]
