# Generated by Django 3.2.7 on 2021-09-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_auto_20210927_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('faculty', 'faculty'), ('hr', 'hr'), ('counsiler', 'counsiler'), ('admin', 'admin')], max_length=40),
        ),
    ]
