# Generated by Django 3.2.7 on 2021-09-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_alter_myuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('faculty', 'faculty'), ('hr', 'hr'), ('counsiler', 'counsiler')], max_length=40),
        ),
    ]
