# Generated by Django 3.2.6 on 2021-09-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='duty_time',
            field=models.TimeField(max_length=5),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='fees',
            field=models.IntegerField(max_length=100),
        ),
    ]
