# Generated by Django 3.2.6 on 2021-09-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadmin', '0002_auto_20210920_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='duty_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='fees',
            field=models.IntegerField(),
        ),
    ]
