# Generated by Django 3.2.6 on 2021-09-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadmin', '0003_auto_20210920_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('other', 'other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_phno',
            field=models.CharField(max_length=10),
        ),
    ]
